const stripeConnectCountries = [
  { value: "AU", name: "Australia" },
  { value: "LV", name: "Latvia" },
  { value: "AT", name: "Austria" },
  { value: "LT", name: "Lithuania" },
  { value: "BE", name: "Belgium" },
  { value: "LU", name: "Luxembourg" },
  { value: "MY", name: "Malaysia" },
  { value: "BG", name: "Bulgaria" },
  { value: "BR", name: "Brazil" },
  { value: "MT", name: "Malta" },
  { value: "CA", name: "Canada" },
  { value: "MX", name: "Mexico" },
  { value: "CY", name: "Cyprus" },
  { value: "NL", name: "Netherlands" },
  { value: "CZ", name: "Czech Republic" },
  { value: "NZ", name: "New Zealand" },
  { value: "DK", name: "Denmark" },
  { value: "NO", name: "Norway" },
  { value: "EE", name: "Estonia" },
  { value: "PL", name: "Poland" },
  { value: "FI", name: "Finland" },
  { value: "PT", name: "Portugal" },
  { value: "FR", name: "France" },
  { value: "RO", name: "Romania" },
  { value: "DE", name: "Germany" },
  { value: "SG", name: "Singapore" },
  { value: "GR", name: "Greece" },
  { value: "SK", name: "Slovakia" },
  { value: "HK", name: "Hong Kong" },
  { value: "SI", name: "Slovenia" },
  { value: "HU", name: "Hungary" },
  { value: "ES", name: "Spain" },
  { value: "SE", name: "Sweden" },
  { value: "IN", name: "India" },
  { value: "IE", name: "Ireland" },
  { value: "CH", name: "Switzerland" },
  { value: "IT", name: "Italy" },
  { value: "GB", name: "United Kingdom" },
  { value: "JP", name: "Japan" },
  { value: "US", name: "United States" },
  { value: "AE", name: "United Arab Emirates" },
];

export default {
  stripeConnectCountries,
};
